/* Generated by GOB (v1.0.9)   (do not edit directly) */



#include "hfm-window.h"
#include "hfm-view-file.h"
#include "icon-hash.h"
#include <gnome.h>
#include <dirent.h>

#include <gtk/gtk.h>

#ifndef __HFM_VIEW_DIRECTORY_H__
#define __HFM_VIEW_DIRECTORY_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define HFM_TYPE_VIEW_DIRECTORY	(hfm_view_directory_get_type())
#define HFM_VIEW_DIRECTORY(obj)	GTK_CHECK_CAST((obj), hfm_view_directory_get_type(), HfmViewDirectory)
#define HFM_VIEW_DIRECTORY_CONST(obj)	GTK_CHECK_CAST((obj), hfm_view_directory_get_type(), HfmViewDirectory const)
#define HFM_VIEW_DIRECTORY_CLASS(klass)	GTK_CHECK_CLASS_CAST((klass), hfm_view_directory_get_type(), HfmViewDirectoryClass)
#define HFM_IS_VIEW_DIRECTORY(obj)	GTK_CHECK_TYPE((obj), hfm_view_directory_get_type ())

#ifdef GTK_CHECK_GET_CLASS
#define HFM_VIEW_DIRECTORY_GET_CLASS(obj)	GTK_CHECK_GET_CLASS((obj), hfm_view_directory_get_type(), HfmViewDirectoryClass)
#else /* !GTK_CHECK_GET_CLASS */
#define HFM_VIEW_DIRECTORY_GET_CLASS(obj)	((HfmViewDirectoryClass *)GTK_OBJECT(obj)->klass)
#endif /* GTK_CHECK_GET_CLASS */

/*
 * Main object structure
 */
#ifndef __TYPEDEF_HFM_VIEW_DIRECTORY__
#define __TYPEDEF_HFM_VIEW_DIRECTORY__
typedef struct _HfmViewDirectory HfmViewDirectory;
#endif
struct _HfmViewDirectory {
	GtkHBox __parent__;
	/*< public >*/
	char * selected;
	char * directory;
	char * fullpath;
	GtkWidget * clist;
	GtkWidget * scrollwindow;
	HfmWindow * parent;
};

/*
 * Class definition
 */
typedef struct _HfmViewDirectoryClass HfmViewDirectoryClass;
struct _HfmViewDirectoryClass {
	GtkHBoxClass __parent__;
};


/*
 * Public methods
 */
GtkType	hfm_view_directory_get_type	(void) G_GNUC_CONST;
GtkWidget * 	hfm_view_directory_new	(HfmWindow * parent,
					gchar * fullpath,
					gchar * directory);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
