/* Generated by GOB (v1.0.9) on Tue Jun 19 23:55:36 2001
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */


#line 1 "hfm-view-mime.gob"

#include <gnome.h>
#include "hfm-window.h"

#line 13 "hfm-view-mime.c"
#define GOB_VERSION_MAJOR 1
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#include <string.h> /* memset() */

#include "hfm-view-mime.h"

#include "hfm-view-mime-private.h"

/* self casting macros */
#define SELF(x) HFM_VIEW_MIME(x)
#define SELF_CONST(x) HFM_VIEW_MIME_CONST(x)
#define IS_SELF(x) HFM_IS_VIEW_MIME(x)
#define SELF_CLASS(x) HFM_VIEW_MIME_CLASS(x)

#define SELF_GET_CLASS(x) HFM_VIEW_MIME_GET_CLASS(x)

/* self typedefs */
typedef HfmViewMime Self;
typedef HfmViewMimeClass SelfClass;

/* GTK_CLASS_TYPE for 1.2<->1.3/2.0 GTK+ compatibility */
#ifndef GTK_CLASS_TYPE
#define GTK_CLASS_TYPE(x) (GTK_OBJECT_CLASS(x)->type)
#endif /* GTK_CLASS_TYPE */

/* here are local prototypes */
static void hfm_view_mime_init (HfmViewMime * o) G_GNUC_UNUSED;
static void hfm_view_mime_class_init (HfmViewMimeClass * c) G_GNUC_UNUSED;
static void hfm_view_mime_populate (HfmViewMime * self, gchar * fullpath) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkHBoxClass *parent_class = NULL;

GtkType
hfm_view_mime_get_type (void)
{
	static GtkType type = 0;

	if (type == 0) {
		static const GtkTypeInfo info = {
			"HfmViewMime",
			sizeof (HfmViewMime),
			sizeof (HfmViewMimeClass),
			(GtkClassInitFunc) hfm_view_mime_class_init,
			(GtkObjectInitFunc) hfm_view_mime_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL
		};

		type = gtk_type_unique (gtk_hbox_get_type(), &info);
	}

	return type;
}

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define populate(args...) hfm_view_mime_populate(args)
#define new(args...) hfm_view_mime_new(args)
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const populate) (HfmViewMime * self, gchar * fullpath) = hfm_view_mime_populate;
static GtkWidget * (* const new) (HfmWindow * parent, gchar * fullpath) = hfm_view_mime_new;

/* a macro for creating a new object of our type */
#define GET_NEW ((HfmViewMime *)gtk_type_new(hfm_view_mime_get_type()))


static void
___destroy(GtkObject *obj_self)
{
#define __GOB_FUNCTION__ "Hfm:View:Mime::destroy"
	HfmViewMime *self = HFM_VIEW_MIME (obj_self);
	if(GTK_OBJECT_CLASS(parent_class)->destroy) \
		(* GTK_OBJECT_CLASS(parent_class)->destroy)(obj_self);
#line 7 "hfm-view-mime.gob"
	if(self->mime_type) { ((*(void (*)(void *))g_free)) (self->mime_type); self->mime_type = NULL; }
#line 95 "hfm-view-mime.c"
#line 8 "hfm-view-mime.gob"
	if(self->fullpath) { ((*(void (*)(void *))g_free)) (self->fullpath); self->fullpath = NULL; }
#line 98 "hfm-view-mime.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
hfm_view_mime_init (HfmViewMime * o)
{
#define __GOB_FUNCTION__ "Hfm:View:Mime::init"
	return;
	o = NULL;
}
#undef __GOB_FUNCTION__
static void 
hfm_view_mime_class_init (HfmViewMimeClass * c)
{
#define __GOB_FUNCTION__ "Hfm:View:Mime::class_init"
	GtkObjectClass *gtk_object_class = (GtkObjectClass*) c;
#ifdef G_OBJECT_CLASS
	GObjectClass *g_object_class = (GObjectClass*) c;
#endif /* G_OBJECT_CLASS */

	parent_class = gtk_type_class (gtk_hbox_get_type ());

	gtk_object_class->destroy = ___destroy;
	return;
	c = NULL;
	gtk_object_class = NULL;
#ifdef G_OBJECT_CLASS
	g_object_class = NULL;
#endif /* G_OBJECT_CLASS */
}
#undef __GOB_FUNCTION__



#line 13 "hfm-view-mime.gob"
static void 
hfm_view_mime_populate (HfmViewMime * self, gchar * fullpath)
#line 138 "hfm-view-mime.c"
{
#define __GOB_FUNCTION__ "Hfm:View:Mime::populate"
#line 13 "hfm-view-mime.gob"
	g_return_if_fail (self != NULL);
#line 13 "hfm-view-mime.gob"
	g_return_if_fail (HFM_IS_VIEW_MIME (self));
#line 145 "hfm-view-mime.c"
{
#line 13 "hfm-view-mime.gob"
	
    GList *mime_keys, *p;
    gchar *insert[] = {NULL, NULL, NULL};
  
    if(self->fullpath)
      g_free(self->fullpath);
    
    self->fullpath = g_strdup((gchar *)fullpath);
    
    if(self->mime_type)
      g_free(self->mime_type);
    
    self->mime_type = g_strdup((gchar *)gnome_mime_type(fullpath));

    gtk_clist_set_column_title(GTK_CLIST(self->clist), 1, self->mime_type);
  
    mime_keys = (GList *)gnome_mime_get_keys(self->mime_type);

    for(p = mime_keys; p != NULL; p = g_list_next(p)) {
      insert[0] = g_strdup((gchar *)p->data);
      insert[1] = g_strdup((gchar *)gnome_mime_get_value(self->mime_type, insert[0]));
      gtk_clist_append(GTK_CLIST(self->clist), insert); 
  
      g_free(insert[0]); insert[0] = NULL;
      g_free(insert[1]); insert[1] = NULL;
    }
  }}
#line 175 "hfm-view-mime.c"
#undef __GOB_FUNCTION__

#line 41 "hfm-view-mime.gob"
GtkWidget * 
hfm_view_mime_new (HfmWindow * parent, gchar * fullpath)
#line 181 "hfm-view-mime.c"
{
#define __GOB_FUNCTION__ "Hfm:View:Mime::new"
{
#line 41 "hfm-view-mime.gob"
	
    gchar *insert[] = {NULL, NULL, NULL};
    HfmViewMime *self = GET_NEW;  
  
    self->parent = parent;
  
    self->clist = gtk_clist_new_with_titles(2, insert);
    
    gtk_clist_set_column_width(GTK_CLIST(self->clist), 0, 160);
    gtk_clist_set_column_width(GTK_CLIST(self->clist), 1, 160);
  
    self->scrollwindow = gtk_scrolled_window_new(NULL, NULL);
    gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW (self->scrollwindow), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  
    /*gtk_signal_connect(GTK_OBJECT(self->clist), "select_row", GTK_SIGNAL_FUNC(file_selected), (gpointer)self);
    gtk_signal_connect(GTK_OBJECT(self->clist), "button_press_event", GTK_SIGNAL_FUNC(file_clicked), (gpointer)self);*/
  
    populate(self, fullpath);
    
    gtk_container_add(GTK_CONTAINER(self->scrollwindow), self->clist);
    gtk_container_add(GTK_CONTAINER(self), self->scrollwindow);
    
    gtk_widget_show_all((GtkWidget *)self);
  
    return (GtkWidget *)self;
  }}
#line 212 "hfm-view-mime.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___hfm_view_mime_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))populate)();
	((void (*)(void))new)();
	___hfm_view_mime_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

