/* Generated by GOB (v1.0.9)   (do not edit directly) */



#include <gnome.h>
#include "hfm-window.h"

#line 1 "hfm-view-mime.gob"
#line 10 "hfm-view-mime-private.h"
#ifndef __HFM_VIEW_MIME_PRIVATE_H__
#define __HFM_VIEW_MIME_PRIVATE_H__

#include "hfm-view-mime.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
