/* Generated by GOB (v1.0.9)   (do not edit directly) */



#include "hfm-window.h"
#include "hfm-view-file.h"
#include "icon-hash.h"
#include <gnome.h>
#include <dirent.h>

#line 1 "hfm-view-directory.gob"
#line 13 "hfm-view-directory-private.h"
#ifndef __HFM_VIEW_DIRECTORY_PRIVATE_H__
#define __HFM_VIEW_DIRECTORY_PRIVATE_H__

#include "hfm-view-directory.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
