/* Generated by GOB (v1.0.9)   (do not edit directly) */



#include <bonobo.h>
#include <gnome.h>
#include "icon-hash.h"

int window_count;

#include <gtk/gtk.h>

#ifndef __HFM_WINDOW_H__
#define __HFM_WINDOW_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define HFM_TYPE_WINDOW	(hfm_window_get_type())
#define HFM_WINDOW(obj)	GTK_CHECK_CAST((obj), hfm_window_get_type(), HfmWindow)
#define HFM_WINDOW_CONST(obj)	GTK_CHECK_CAST((obj), hfm_window_get_type(), HfmWindow const)
#define HFM_WINDOW_CLASS(klass)	GTK_CHECK_CLASS_CAST((klass), hfm_window_get_type(), HfmWindowClass)
#define HFM_IS_WINDOW(obj)	GTK_CHECK_TYPE((obj), hfm_window_get_type ())

#ifdef GTK_CHECK_GET_CLASS
#define HFM_WINDOW_GET_CLASS(obj)	GTK_CHECK_GET_CLASS((obj), hfm_window_get_type(), HfmWindowClass)
#else /* !GTK_CHECK_GET_CLASS */
#define HFM_WINDOW_GET_CLASS(obj)	((HfmWindowClass *)GTK_OBJECT(obj)->klass)
#endif /* GTK_CHECK_GET_CLASS */

/*
 * Main object structure
 */
#ifndef __TYPEDEF_HFM_WINDOW__
#define __TYPEDEF_HFM_WINDOW__
typedef struct _HfmWindow HfmWindow;
#endif
struct _HfmWindow {
	BonoboWindow __parent__;
	/*< public >*/
	BonoboUIContainer * uic;
	GtkWidget * scrollwindow;
	GtkWidget * vbox;
	GtkWidget * hbox;
	GList * views;
};

/*
 * Class definition
 */
typedef struct _HfmWindowClass HfmWindowClass;
struct _HfmWindowClass {
	BonoboWindowClass __parent__;
};


/*
 * Public methods
 */
GtkType	hfm_window_get_type	(void) G_GNUC_CONST;
void 	hfm_window_add_view	(HfmWindow * self,
					GtkWidget * widget);
void 	hfm_window_add_view_after	(HfmWindow * self,
					GtkWidget * current,
					GtkWidget * new_widget);
GtkWidget * 	hfm_window_new	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
