/* Generated by GOB (v1.0.9) on Tue Jun 19 23:22:25 2001
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */


#line 1 "hfm-view-directory.gob"

#include "hfm-window.h"
#include "hfm-view-file.h"
#include "icon-hash.h"
#include <gnome.h>
#include <dirent.h>

#line 16 "hfm-view-directory.c"
#define GOB_VERSION_MAJOR 1
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#include <string.h> /* memset() */

#include "hfm-view-directory.h"

#include "hfm-view-directory-private.h"

/* self casting macros */
#define SELF(x) HFM_VIEW_DIRECTORY(x)
#define SELF_CONST(x) HFM_VIEW_DIRECTORY_CONST(x)
#define IS_SELF(x) HFM_IS_VIEW_DIRECTORY(x)
#define SELF_CLASS(x) HFM_VIEW_DIRECTORY_CLASS(x)

#define SELF_GET_CLASS(x) HFM_VIEW_DIRECTORY_GET_CLASS(x)

/* self typedefs */
typedef HfmViewDirectory Self;
typedef HfmViewDirectoryClass SelfClass;

/* GTK_CLASS_TYPE for 1.2<->1.3/2.0 GTK+ compatibility */
#ifndef GTK_CLASS_TYPE
#define GTK_CLASS_TYPE(x) (GTK_OBJECT_CLASS(x)->type)
#endif /* GTK_CLASS_TYPE */

/* here are local prototypes */
static void hfm_view_directory_init (HfmViewDirectory * o) G_GNUC_UNUSED;
static void hfm_view_directory_class_init (HfmViewDirectoryClass * c) G_GNUC_UNUSED;
static void hfm_view_directory_selected (GtkWidget * src, gint row, gint column, GdkEventButton * event, gpointer user_data) G_GNUC_UNUSED;
static void hfm_view_directory_populate (HfmViewDirectory * self, gchar * fullpath, gchar * directory) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkHBoxClass *parent_class = NULL;

GtkType
hfm_view_directory_get_type (void)
{
	static GtkType type = 0;

	if (type == 0) {
		static const GtkTypeInfo info = {
			"HfmViewDirectory",
			sizeof (HfmViewDirectory),
			sizeof (HfmViewDirectoryClass),
			(GtkClassInitFunc) hfm_view_directory_class_init,
			(GtkObjectInitFunc) hfm_view_directory_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL
		};

		type = gtk_type_unique (gtk_hbox_get_type(), &info);
	}

	return type;
}

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define selected(args...) hfm_view_directory_selected(args)
#define populate(args...) hfm_view_directory_populate(args)
#define new(args...) hfm_view_directory_new(args)
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const selected) (GtkWidget * src, gint row, gint column, GdkEventButton * event, gpointer user_data) = hfm_view_directory_selected;
static void (* const populate) (HfmViewDirectory * self, gchar * fullpath, gchar * directory) = hfm_view_directory_populate;
static GtkWidget * (* const new) (HfmWindow * parent, gchar * fullpath, gchar * directory) = hfm_view_directory_new;

/* a macro for creating a new object of our type */
#define GET_NEW ((HfmViewDirectory *)gtk_type_new(hfm_view_directory_get_type()))


static void
___destroy(GtkObject *obj_self)
{
#define __GOB_FUNCTION__ "Hfm:View:Directory::destroy"
	HfmViewDirectory *self = HFM_VIEW_DIRECTORY (obj_self);
	if(GTK_OBJECT_CLASS(parent_class)->destroy) \
		(* GTK_OBJECT_CLASS(parent_class)->destroy)(obj_self);
#line 10 "hfm-view-directory.gob"
	if(self->selected) { ((*(void (*)(void *))g_free)) (self->selected); self->selected = NULL; }
#line 101 "hfm-view-directory.c"
#line 11 "hfm-view-directory.gob"
	if(self->directory) { ((*(void (*)(void *))g_free)) (self->directory); self->directory = NULL; }
#line 104 "hfm-view-directory.c"
#line 12 "hfm-view-directory.gob"
	if(self->fullpath) { ((*(void (*)(void *))g_free)) (self->fullpath); self->fullpath = NULL; }
#line 107 "hfm-view-directory.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
hfm_view_directory_init (HfmViewDirectory * o)
{
#define __GOB_FUNCTION__ "Hfm:View:Directory::init"
	return;
	o = NULL;
}
#undef __GOB_FUNCTION__
static void 
hfm_view_directory_class_init (HfmViewDirectoryClass * c)
{
#define __GOB_FUNCTION__ "Hfm:View:Directory::class_init"
	GtkObjectClass *gtk_object_class = (GtkObjectClass*) c;
#ifdef G_OBJECT_CLASS
	GObjectClass *g_object_class = (GObjectClass*) c;
#endif /* G_OBJECT_CLASS */

	parent_class = gtk_type_class (gtk_hbox_get_type ());

	gtk_object_class->destroy = ___destroy;
	return;
	c = NULL;
	gtk_object_class = NULL;
#ifdef G_OBJECT_CLASS
	g_object_class = NULL;
#endif /* G_OBJECT_CLASS */
}
#undef __GOB_FUNCTION__



#line 17 "hfm-view-directory.gob"
static void 
hfm_view_directory_selected (GtkWidget * src, gint row, gint column, GdkEventButton * event, gpointer user_data)
#line 147 "hfm-view-directory.c"
{
#define __GOB_FUNCTION__ "Hfm:View:Directory::selected"
{
#line 17 "hfm-view-directory.gob"
	
    HfmViewDirectory *self = (HfmViewDirectory *)user_data;
    GtkWidget *next = NULL;
    gchar *fullpath;
    gchar *file;
    
    gtk_clist_get_text(GTK_CLIST(self->clist), row, 1, &file);  
  
    if(self->selected)
      g_free(self->selected);
     
    self->selected = g_strdup(file);
    
    fullpath = g_strdup_printf("%s/%s", self->fullpath, self->selected);
    
    if(is_directory(fullpath))
      next = hfm_view_directory_new(self->parent, fullpath, self->selected);
    else
      next = hfm_view_file_new(self->parent, fullpath, self->selected);
    
    hfm_window_add_view_after(self->parent, GTK_WIDGET(self), next);
  
    g_free(fullpath);
  }}
#line 176 "hfm-view-directory.c"
#undef __GOB_FUNCTION__

#line 42 "hfm-view-directory.gob"
static void 
hfm_view_directory_populate (HfmViewDirectory * self, gchar * fullpath, gchar * directory)
#line 182 "hfm-view-directory.c"
{
#define __GOB_FUNCTION__ "Hfm:View:Directory::populate"
#line 42 "hfm-view-directory.gob"
	g_return_if_fail (self != NULL);
#line 42 "hfm-view-directory.gob"
	g_return_if_fail (HFM_IS_VIEW_DIRECTORY (self));
#line 189 "hfm-view-directory.c"
{
#line 42 "hfm-view-directory.gob"
	
    DIR *cur_dir = NULL;
    struct dirent *dir_entry = NULL;
    gchar *insert[] = {NULL, NULL, NULL};
    GList *directory_list = NULL, *p = NULL;
    int row = 0;
    struct icon_hash *icon = NULL;
  
    if(self->fullpath)
      g_free(self->fullpath);
    
    self->fullpath = g_strdup(fullpath);
    
    if(self->directory)
      g_free(self->directory);
    
    self->directory = g_strdup(directory);
    
    gtk_clist_set_column_title(GTK_CLIST(self->clist), 1, self->directory);
  
    cur_dir = opendir(self->fullpath);
  
    if(cur_dir) {   
      while((dir_entry = readdir(cur_dir))) {
        if(dir_entry->d_name[0] == '.') 
          continue;
        directory_list = g_list_insert_sorted(directory_list, g_strdup(dir_entry->d_name), (GCompareFunc)g_strncasecmp);
      }
    
      for(p = directory_list; p != NULL; p = g_list_next(p)) {
        insert[1] = (gchar *)p->data;
        gtk_clist_append(GTK_CLIST(self->clist), insert);
        icon = get_icon_for_file(self->fullpath, p->data);
        gtk_clist_set_pixmap(GTK_CLIST(self->clist), row, 0, icon->pixmap, icon->mask);
        g_free(p->data);
        row++;
      }
    
      g_list_free(directory_list);
      
      closedir(cur_dir);
    }
  }}
#line 235 "hfm-view-directory.c"
#undef __GOB_FUNCTION__

#line 86 "hfm-view-directory.gob"
GtkWidget * 
hfm_view_directory_new (HfmWindow * parent, gchar * fullpath, gchar * directory)
#line 241 "hfm-view-directory.c"
{
#define __GOB_FUNCTION__ "Hfm:View:Directory::new"
{
#line 86 "hfm-view-directory.gob"
	
    HfmViewDirectory *self = GET_NEW;
    gchar *insert[] = {NULL, NULL, NULL};
    
    self->parent = parent;
    
    self->clist = gtk_clist_new_with_titles(2, insert);
    gtk_clist_set_column_width(GTK_CLIST(self->clist), 0, 15);
    gtk_clist_set_column_width(GTK_CLIST(self->clist), 1, 205);
    
    self->scrollwindow = gtk_scrolled_window_new(NULL, NULL);
    gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(self->scrollwindow), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
    
    gtk_container_add(GTK_CONTAINER(self->scrollwindow), self->clist);
    gtk_container_add(GTK_CONTAINER(self), self->scrollwindow);
    
    gtk_widget_show_all(GTK_WIDGET(self));
    
    gtk_signal_connect(GTK_OBJECT(self->clist), "select_row", GTK_SIGNAL_FUNC(selected), (gpointer)self);
    /*gtk_signal_connect(GTK_OBJECT(self->clist), "button_press_event", GTK_SIGNAL_FUNC(clicked), (gpointer)self);*/
  
    populate(self, fullpath, directory);
    
    return (GtkWidget *)self;
  }}
#line 271 "hfm-view-directory.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___hfm_view_directory_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))selected)();
	((void (*)(void))populate)();
	((void (*)(void))new)();
	___hfm_view_directory_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

