/* Generated by GOB (v1.0.9)   (do not edit directly) */



#include <gnome.h>
#include "hfm-window.h"

#include <gtk/gtk.h>

#ifndef __HFM_VIEW_MIME_H__
#define __HFM_VIEW_MIME_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define HFM_TYPE_VIEW_MIME	(hfm_view_mime_get_type())
#define HFM_VIEW_MIME(obj)	GTK_CHECK_CAST((obj), hfm_view_mime_get_type(), HfmViewMime)
#define HFM_VIEW_MIME_CONST(obj)	GTK_CHECK_CAST((obj), hfm_view_mime_get_type(), HfmViewMime const)
#define HFM_VIEW_MIME_CLASS(klass)	GTK_CHECK_CLASS_CAST((klass), hfm_view_mime_get_type(), HfmViewMimeClass)
#define HFM_IS_VIEW_MIME(obj)	GTK_CHECK_TYPE((obj), hfm_view_mime_get_type ())

#ifdef GTK_CHECK_GET_CLASS
#define HFM_VIEW_MIME_GET_CLASS(obj)	GTK_CHECK_GET_CLASS((obj), hfm_view_mime_get_type(), HfmViewMimeClass)
#else /* !GTK_CHECK_GET_CLASS */
#define HFM_VIEW_MIME_GET_CLASS(obj)	((HfmViewMimeClass *)GTK_OBJECT(obj)->klass)
#endif /* GTK_CHECK_GET_CLASS */

/*
 * Main object structure
 */
#ifndef __TYPEDEF_HFM_VIEW_MIME__
#define __TYPEDEF_HFM_VIEW_MIME__
typedef struct _HfmViewMime HfmViewMime;
#endif
struct _HfmViewMime {
	GtkHBox __parent__;
	/*< public >*/
	gchar * mime_type;
	gchar * fullpath;
	GtkWidget * clist;
	GtkWidget * scrollwindow;
	HfmWindow * parent;
};

/*
 * Class definition
 */
typedef struct _HfmViewMimeClass HfmViewMimeClass;
struct _HfmViewMimeClass {
	GtkHBoxClass __parent__;
};


/*
 * Public methods
 */
GtkType	hfm_view_mime_get_type	(void) G_GNUC_CONST;
GtkWidget * 	hfm_view_mime_new	(HfmWindow * parent,
					gchar * fullpath);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
