/* Generated by GOB (v1.0.9)   (do not edit directly) */



#include <gnome.h>
#include <time.h>
#include <sys/stat.h>
#include "hfm-window.h"
#include "hfm-view-mime.h"

#line 1 "hfm-view-file.gob"
#line 13 "hfm-view-file-private.h"
#ifndef __HFM_VIEW_FILE_PRIVATE_H__
#define __HFM_VIEW_FILE_PRIVATE_H__

#include "hfm-view-file.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
