/* Generated by GOB (v1.0.9) on Tue Jun 19 23:53:08 2001
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */


#line 1 "hfm-view-file.gob"

#include <gnome.h>
#include <sys/stat.h>
#include "hfm-window.h"
#include "hfm-view-mime.h"

#line 15 "hfm-view-file.c"
#define GOB_VERSION_MAJOR 1
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#include <string.h> /* memset() */

#include "hfm-view-file.h"

#include "hfm-view-file-private.h"


#line 8 "hfm-view-file.gob"

#define UNIT_COUNT 4
gchar* unit[4] = { "bytes", "k","MB","GB" };

#line 32 "hfm-view-file.c"
/* self casting macros */
#define SELF(x) HFM_VIEW_FILE(x)
#define SELF_CONST(x) HFM_VIEW_FILE_CONST(x)
#define IS_SELF(x) HFM_IS_VIEW_FILE(x)
#define SELF_CLASS(x) HFM_VIEW_FILE_CLASS(x)

#define SELF_GET_CLASS(x) HFM_VIEW_FILE_GET_CLASS(x)

/* self typedefs */
typedef HfmViewFile Self;
typedef HfmViewFileClass SelfClass;

/* GTK_CLASS_TYPE for 1.2<->1.3/2.0 GTK+ compatibility */
#ifndef GTK_CLASS_TYPE
#define GTK_CLASS_TYPE(x) (GTK_OBJECT_CLASS(x)->type)
#endif /* GTK_CLASS_TYPE */

/* here are local prototypes */
static void hfm_view_file_init (HfmViewFile * o) G_GNUC_UNUSED;
static void hfm_view_file_class_init (HfmViewFileClass * c) G_GNUC_UNUSED;
static void hfm_view_file_selected (GtkWidget * src, gint row, gint column, GdkEventButton * event, gpointer user_data) G_GNUC_UNUSED;
static void hfm_view_file_action_selected (GtkWidget * src, gpointer user_data) G_GNUC_UNUSED;
static void hfm_view_file_add_action_buttons (HfmViewFile * self) G_GNUC_UNUSED;
static void hfm_view_file_populate (HfmViewFile * self, gchar * fullpath, gchar * file) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkHBoxClass *parent_class = NULL;

GtkType
hfm_view_file_get_type (void)
{
	static GtkType type = 0;

	if (type == 0) {
		static const GtkTypeInfo info = {
			"HfmViewFile",
			sizeof (HfmViewFile),
			sizeof (HfmViewFileClass),
			(GtkClassInitFunc) hfm_view_file_class_init,
			(GtkObjectInitFunc) hfm_view_file_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL
		};

		type = gtk_type_unique (gtk_hbox_get_type(), &info);
	}

	return type;
}

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define selected(args...) hfm_view_file_selected(args)
#define action_selected(args...) hfm_view_file_action_selected(args)
#define add_action_buttons(args...) hfm_view_file_add_action_buttons(args)
#define populate(args...) hfm_view_file_populate(args)
#define new(args...) hfm_view_file_new(args)
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const selected) (GtkWidget * src, gint row, gint column, GdkEventButton * event, gpointer user_data) = hfm_view_file_selected;
static void (* const action_selected) (GtkWidget * src, gpointer user_data) = hfm_view_file_action_selected;
static void (* const add_action_buttons) (HfmViewFile * self) = hfm_view_file_add_action_buttons;
static void (* const populate) (HfmViewFile * self, gchar * fullpath, gchar * file) = hfm_view_file_populate;
static GtkWidget * (* const new) (HfmWindow * parent, gchar * fullpath, gchar * file) = hfm_view_file_new;

/* a macro for creating a new object of our type */
#define GET_NEW ((HfmViewFile *)gtk_type_new(hfm_view_file_get_type()))


static void
___destroy(GtkObject *obj_self)
{
#define __GOB_FUNCTION__ "Hfm:View:File::destroy"
	HfmViewFile *self = HFM_VIEW_FILE (obj_self);
	if(GTK_OBJECT_CLASS(parent_class)->destroy) \
		(* GTK_OBJECT_CLASS(parent_class)->destroy)(obj_self);
#line 14 "hfm-view-file.gob"
	if(self->file) { ((*(void (*)(void *))g_free)) (self->file); self->file = NULL; }
#line 113 "hfm-view-file.c"
#line 15 "hfm-view-file.gob"
	if(self->fullpath) { ((*(void (*)(void *))g_free)) (self->fullpath); self->fullpath = NULL; }
#line 116 "hfm-view-file.c"
#line 20 "hfm-view-file.gob"
	if(self->buttons) { ((*(void (*)(void *))g_list_free)) (self->buttons); self->buttons = NULL; }
#line 119 "hfm-view-file.c"
#line 21 "hfm-view-file.gob"
	if(self->commands) { ((*(void (*)(void *))g_list_free)) (self->commands); self->commands = NULL; }
#line 122 "hfm-view-file.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
hfm_view_file_init (HfmViewFile * o)
{
#define __GOB_FUNCTION__ "Hfm:View:File::init"
	return;
	o = NULL;
}
#undef __GOB_FUNCTION__
static void 
hfm_view_file_class_init (HfmViewFileClass * c)
{
#define __GOB_FUNCTION__ "Hfm:View:File::class_init"
	GtkObjectClass *gtk_object_class = (GtkObjectClass*) c;
#ifdef G_OBJECT_CLASS
	GObjectClass *g_object_class = (GObjectClass*) c;
#endif /* G_OBJECT_CLASS */

	parent_class = gtk_type_class (gtk_hbox_get_type ());

	gtk_object_class->destroy = ___destroy;
	return;
	c = NULL;
	gtk_object_class = NULL;
#ifdef G_OBJECT_CLASS
	g_object_class = NULL;
#endif /* G_OBJECT_CLASS */
}
#undef __GOB_FUNCTION__



#line 24 "hfm-view-file.gob"
static void 
hfm_view_file_selected (GtkWidget * src, gint row, gint column, GdkEventButton * event, gpointer user_data)
#line 162 "hfm-view-file.c"
{
#define __GOB_FUNCTION__ "Hfm:View:File::selected"
{
#line 24 "hfm-view-file.gob"
	
    HfmViewFile *self = (HfmViewFile *)user_data;
 
    if(row == 2) {
      hfm_window_add_view_after(self->parent, GTK_WIDGET(self), hfm_view_mime_new(self->parent, self->fullpath));
    }
  }}
#line 174 "hfm-view-file.c"
#undef __GOB_FUNCTION__

#line 32 "hfm-view-file.gob"
static void 
hfm_view_file_action_selected (GtkWidget * src, gpointer user_data)
#line 180 "hfm-view-file.c"
{
#define __GOB_FUNCTION__ "Hfm:View:File::action_selected"
{
#line 32 "hfm-view-file.gob"
	
    printf("Executing %s\n", (char *)user_data);
  
    system((gchar *)user_data);
  }}
#line 190 "hfm-view-file.c"
#undef __GOB_FUNCTION__

#line 38 "hfm-view-file.gob"
static void 
hfm_view_file_add_action_buttons (HfmViewFile * self)
#line 196 "hfm-view-file.c"
{
#define __GOB_FUNCTION__ "Hfm:View:File::add_action_buttons"
#line 38 "hfm-view-file.gob"
	g_return_if_fail (self != NULL);
#line 38 "hfm-view-file.gob"
	g_return_if_fail (HFM_IS_VIEW_FILE (self));
#line 203 "hfm-view-file.c"
{
#line 38 "hfm-view-file.gob"
	
    GtkWidget *button;
    gchar *mime_type, *actions;
    gchar **key_pair, **action_pair, *temp_label;
    char *run_command = NULL, *command_location = NULL;
    int i = 0;
  
    mime_type = g_strdup(gnome_mime_type_of_file(self->fullpath));
    actions = g_strdup(gnome_mime_get_value(mime_type, "hfm-action"));
  
    if(actions) {
      key_pair = g_strsplit(actions, ",", 0);
    
      for(i = 0; key_pair[i] != NULL; i++) {
        action_pair = g_strsplit(key_pair[i], "=", 0);
        if(action_pair[0] && action_pair[1]) {
          temp_label = g_strdup_printf("%s (%s)", g_strstrip(action_pair[0]), g_strstrip(action_pair[1]));
          
          button = gtk_button_new_with_label(temp_label);
          
          g_free(temp_label);
        
          command_location = index(action_pair[1], '%');
          if(command_location != NULL)
            command_location[0] = '\0';
  
          run_command = g_strdup_printf("%s \"%s\" &", g_strstrip(action_pair[1]), self->fullpath);
  
          gtk_signal_connect(GTK_OBJECT(button), "clicked", GTK_SIGNAL_FUNC(action_selected), (char *)run_command);
          gtk_widget_set_usize(GTK_WIDGET(button), 100, 25);
          self->buttons = g_list_append(self->buttons, (gpointer)button);
          self->commands = g_list_append(self->commands, (gpointer)run_command);
          gtk_box_pack_start(GTK_BOX(self->vbox), button, FALSE, FALSE, 0);
          gtk_widget_show(button);
        }
        g_strfreev(action_pair);
      }
    
      g_strfreev(key_pair);
      g_free(actions);
    }
  
    g_free(mime_type);
  }}
#line 250 "hfm-view-file.c"
#undef __GOB_FUNCTION__

#line 83 "hfm-view-file.gob"
static void 
hfm_view_file_populate (HfmViewFile * self, gchar * fullpath, gchar * file)
#line 256 "hfm-view-file.c"
{
#define __GOB_FUNCTION__ "Hfm:View:File::populate"
#line 83 "hfm-view-file.gob"
	g_return_if_fail (self != NULL);
#line 83 "hfm-view-file.gob"
	g_return_if_fail (HFM_IS_VIEW_FILE (self));
#line 263 "hfm-view-file.c"
{
#line 83 "hfm-view-file.gob"
	
    gchar *insert[] = {NULL, NULL, NULL};
    gchar *bonobo_moniker = NULL;
    gfloat size = 0;
    int count = 0;
    struct stat *stat_entry = NULL;
    
    if(self->fullpath)
      g_free(self->fullpath);
      
    self->fullpath = g_strdup(fullpath);
    
    if(self->file)
      g_free(self->file);
      
    self->file = g_strdup(file);
    
    gtk_clist_set_column_title(GTK_CLIST(self->clist), 0, "info");
    gtk_clist_set_column_title(GTK_CLIST(self->clist), 1, "");
    
    add_action_buttons(self);
    
    bonobo_moniker = g_strdup_printf("file:%s", self->fullpath);
    
    if(self->bonobo_preview)
      gtk_widget_destroy(self->bonobo_preview);
    
    self->bonobo_preview = bonobo_widget_new_control(bonobo_moniker, BONOBO_OBJREF(self->parent->uic));
    if(!self->bonobo_preview)
      self->bonobo_preview = gtk_label_new("No preview available.");
    
    g_free(bonobo_moniker);
    
    gtk_container_add(GTK_CONTAINER(self->vbox), self->bonobo_preview);
        
    stat_entry = g_malloc(sizeof(struct stat));
    
    stat(self->fullpath, stat_entry);

    for ( size = (gfloat)stat_entry->st_size; size >= 1024 && count < UNIT_COUNT ; size /= 1024)
      count++;
    
    g_free(stat_entry);
    
    insert[0] = "filename";
    insert[1] = self->file;
    gtk_clist_append(GTK_CLIST(self->clist), insert);

    insert[0] = "size";
    insert[1] = g_strdup_printf("%.01f %s", size, unit[count]);
    gtk_clist_append(GTK_CLIST(self->clist), insert);

    g_free(insert[1]);
    
    insert[0] = "mime-type";
    insert[1] = g_strdup(gnome_mime_type_of_file(self->fullpath));
    gtk_clist_append(GTK_CLIST(self->clist), insert);

    g_free(insert[1]);
  }}
#line 326 "hfm-view-file.c"
#undef __GOB_FUNCTION__

#line 144 "hfm-view-file.gob"
GtkWidget * 
hfm_view_file_new (HfmWindow * parent, gchar * fullpath, gchar * file)
#line 332 "hfm-view-file.c"
{
#define __GOB_FUNCTION__ "Hfm:View:File::new"
{
#line 144 "hfm-view-file.gob"
	
    gchar *insert[] = {NULL, NULL, NULL};
    HfmViewFile *self = GET_NEW;  
  
    self->parent = parent;
  
    self->clist = gtk_clist_new_with_titles(2, insert);
    
    gtk_clist_set_column_width(GTK_CLIST(self->clist), 0, 60);
    gtk_clist_set_column_width(GTK_CLIST(self->clist), 1, 160); 
  
    self->scrollwindow = gtk_scrolled_window_new(NULL, NULL);
    gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW (self->scrollwindow), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  
    self->vbox = gtk_vbox_new(FALSE, 0);
  
    gtk_signal_connect(GTK_OBJECT(self->clist), "select_row", GTK_SIGNAL_FUNC(selected), (gpointer)self);
    /*gtk_signal_connect(GTK_OBJECT(self->clist), "button_press_event", GTK_SIGNAL_FUNC(file_clicked), (gpointer)self);*/
  
    gtk_scrolled_window_add_with_viewport(GTK_SCROLLED_WINDOW(self->scrollwindow), self->vbox);
    gtk_container_add(GTK_CONTAINER(self->vbox), self->clist);
    gtk_container_add(GTK_CONTAINER(self), self->scrollwindow);
  
    populate(self, fullpath, file);

    gtk_widget_show_all((GtkWidget *)self);
  
    return (GtkWidget *)self;
  }}
#line 366 "hfm-view-file.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___hfm_view_file_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))selected)();
	((void (*)(void))action_selected)();
	((void (*)(void))add_action_buttons)();
	((void (*)(void))populate)();
	((void (*)(void))new)();
	___hfm_view_file_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

