/* Generated by GOB (v1.0.9)   (do not edit directly) */



#include <bonobo.h>
#include <gnome.h>
#include "icon-hash.h"

int window_count;

#line 1 "hfm-window.gob"
#line 13 "hfm-window-private.h"
#ifndef __HFM_WINDOW_PRIVATE_H__
#define __HFM_WINDOW_PRIVATE_H__

#include "hfm-window.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
